### PR TITLE
Fix floating point issues

### PR DESCRIPTION
**Pull request by xxczaki**
> Related to #1 

## Description

To avoid floating point issues, I think it would be a good idea to use a well tested & lightweight library, such as [big.js](https://github.com/MikeMcl/big.js/).

This pull request implements that :smile:

cc @ThisIsMissEm - What do you think?

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
You probably don't need the dependency of big.js; As all cash values can usually only be represented down to the cent (i.e., they're decimalised) — so usually you can represent money as an Integer of cents; here you accept an API of dollars or decimal currency, so, first we multiplied by 100 to get cents.

The issue mentioned in the original pull request is that the getRate method also has potential for floating point math errors: https://github.com/xxczaki/cashify/blob/4580e9eb9fb421405f8e5fa2195dc6832063aafa/src/index.ts#L11-L28

**Comment by xxczaki** [comment]
@ThisIsMissEm So the best solution would be to refactor the `getRate` method to use cents integer and then simply convert the final result to decimal (eg. 1.33 dollar/euro etc)?

**Comment by xxczaki** [comment]
I don't think I understand everything correctly, but this should avoid floating point errors, right?

I know it might look like a mess, but basically it makes all calculations on cents (integer) and then converts the result to decimal.

```ts
const getRate = ({base, rates, from, to}: Options): number => {
	// If `from` equals `base`, return the basic exchange rate for the `to` currency
	if (from === base && hasKey(rates, to)) {
		return rates[to];
	}

	// If `to` equals `base`, return the basic inverse rate of the `from` currency
	if (to === base && hasKey(rates, from)) {
		return (10000 / (rates[from] * 100)) / 100;
	}

	/**
		Otherwise, return the `to` rate multipled by the inverse of the `from` rate to get the
		relative exchange rate between the two currencies
	*/
	if (hasKey(rates, from) && hasKey(rates, to)) {
		return ((rates[to] * 100) * (100 / (rates[from] * 100))) / 100;
	}

	throw new Error('`rates` object does not contain either `from` or `to` currency!');
};
```

**Comment by ThisIsMissEm** [comment]
That could work, in some cases, but it depends on what your exchange rates are; as exchange rates are essentially ratios A:B, there's a high probably that they'll maybe have greater precision like at the moment €1 = US$1.12109, sure you could round it to US$1.12, but that's only okay if you're talking about €1; if you're talking about €100,000 then you'd be significantly out: US$112,109 vs US$112,000 a difference of US$109

So if anything, it's on calculating the exchange rate ratio that you'd want to use a floating point safe mathematical library (e.g., Big.js), for the maths of converting amounts, just doing the `value * 100` is pretty safe, as it's not entirely usual to work with fractions of cents, usually money will be rounded to the nearest cent.

**Comment by xxczaki** [comment]
Let's stick with `value * 100`, at least for now :smile:

**Comment by ThisIsMissEm** [comment]
@xxczaki no, you can't us cents for the rates — as they're ratios, not monetary values; You'd want to use Big.js to calculate the rates, and then you could calculate the value with the a standard multiplication on the cents of the value.

Essentially, as long as you work with money as cents and then conversion rates as floating-point-safe values, then you'll be fine.

**Comment by ThisIsMissEm** [comment]
@xxczaki but also, if you do treat ratios as cents, like you've done here, then you'll likely want to add a disclaimer that this can only support two decimal places in the conversion rates, anything more will introduce floating point errors

**Pull request merged**
